apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: custom-rules
  namespace: monitoring
  labels:
    prometheus: kube-prometheus
    app: kube-prometheus-stack
    release: prometheus-monitoring
spec:
  groups:
    - name: custom-rules
      rules:
      - alert: HostHighCPULoad
        expr: 1 - (avg without (cpu) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) > .80
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Host {{ $labels.instance }} CPU load is high"
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
      - alert: KubernetesPodCrashLooping
        expr: increase(kube_pod_container_status_restarts_total[5m]) >= 2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Kubernetes pod crash looping (instance {{ $labels.instance }})
          description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

